"""Local persistence adapters."""

from autorentledger.storage.sqlite import (
    AllocationBalance,
    AllocationExceedsObligationError,
    AllocationExceedsPaymentError,
    AllocationObligationNotFoundError,
    AllocationPairExistsError,
    AllocationPaymentNotFoundError,
    PayerAliasRecord,
    PayerRecord,
    PaymentAllocationRecord,
    PaymentAllocationSummary,
    PaymentEventRecord,
    PaymentSenderCount,
    RawEmailRecord,
    RentAccountPayerRecord,
    RentAccountRecord,
    RentAccountSummary,
    RentObligationRecord,
    RentObligationSummary,
    SQLiteAllocationRepository,
    SQLiteObligationRepository,
    SQLitePayerRepository,
    SQLitePaymentEventRepository,
    SQLiteRawEmailRepository,
    SQLiteRentalRepository,
    UnitRecord,
)

__all__ = [
    "AllocationBalance",
    "AllocationExceedsObligationError",
    "AllocationExceedsPaymentError",
    "AllocationObligationNotFoundError",
    "AllocationPairExistsError",
    "AllocationPaymentNotFoundError",
    "PayerAliasRecord",
    "PayerRecord",
    "PaymentAllocationRecord",
    "PaymentAllocationSummary",
    "PaymentEventRecord",
    "PaymentSenderCount",
    "RawEmailRecord",
    "RentAccountPayerRecord",
    "RentAccountRecord",
    "RentAccountSummary",
    "RentObligationRecord",
    "RentObligationSummary",
    "SQLiteAllocationRepository",
    "SQLiteObligationRepository",
    "SQLitePayerRepository",
    "SQLitePaymentEventRepository",
    "SQLiteRawEmailRepository",
    "SQLiteRentalRepository",
    "UnitRecord",
]
